### PR TITLE
[fix] Fixed matchRegexp validation

### PR DESCRIPTION
**Pull request by mrazicz**
Hi,

I just ran into issue with matchRegexp validation. So I fixed it, and here is a pull request. Hope you will like it and will be merged into master.

### CODE REVIEW

**Comment by NewOldMax** [comment]
Hi, @mrazicz 
Thanks for your PR :) What kind of issue you get?
And can you run eslint for your code? 😄

**Comment by mrazicz** [comment]
Hi,

match Regexp does not work at all.

`validators: ["matchRegexp:^[0-9]{8}$"]`

Internally you split that validator by ":" and then you pass "^[0-9]{8}$" directly to matchRegexp function as String. But string doesn't have method test() so it fails.

Eslint - sure. I'm kind of new to React and javascript, so I don't know about these features :)

**Comment by mrazicz** [comment]
Here it is. Eslint output is empty now :) #9530192

**Comment by NewOldMax** [comment]
All fine, thanks :)

**Pull request merged**
